Added support for new Nimble 7.x Predicate API
RxSwiftCommunity/RxNimble pull request #21
Opened 2017-06-01 08:30 UTC by vhbit

2017-06-01 18:10 UTC, ashfurrow requested changes
Looks great! Just a couple of minor tweaks. Thanks!

2017-06-01 18:10 UTC, ashfurrow commented on RxNimble.podspec
> +  s.dependency "Nimble", "~> 7.0"
Since this is a major bump to a dependency, we'll need to upgrade RxNimble to 3.0.0 instead of 2.0.1.

2017-06-01 18:10 UTC, ashfurrow commented on Source/RxNimble.swift
> +            matches = expectedValue == nil
Let's wrap these boolean expressions in parens, like `matches = (expectedValue == nil)`

2017-06-02 07:37 UTC, vhbit commented on RxNimble.podspec
> +  s.dependency "Nimble", "~> 7.0"
Done.

2017-06-02 07:39 UTC, vhbit commented
@ashfurrow everything is fixed now

2017-06-02 17:21 UTC, merged

2017-06-02 17:28 UTC, ashfurrow commented
Okay, this has been pushed as 3.0.0 for CocoaPods and Carthage users 👍